const marketTypesDetails = {
	DistrictCommodityGird : {
		name : "जिल्हा शेतमाल निहाय/DistrictCommodityGird",
		tableId : "DistrictCommodityGird",
		SelectOptionId : "drpDistrictCommodity",
		tableName : "DistrictCommodityGird",
		subTabID : "DistrictCommodityWiseGirdID",
		DropdownOptions : [
			{ name: "अकोला", code: "32" },
			{ name: "अमरावती", code: "33" },
			{ name: "अहिल्यानगर", code: "16" },
			{ name: "कोल्हापूर", code: "20" },
			{ name: "गडचिरोली", code: "38" },
			{ name: "गोंदिया", code: "44" },
			{ name: "चंद्रपुर", code: "37" },
			{ name: "छत्रपती संभाजीनगर", code: "25" },
			{ name: "जळगाव", code: "18" },
			{ name: "जालना", code: "27" },
			{ name: "ठाणे", code: "14" },
			{ name: "धाराशिव", code: "30" },
			{ name: "धुळे", code: "17" },
			{ name: "नंदुरबार", code: "41" },
			{ name: "नांदेड", code: "29" },
			{ name: "नागपूर", code: "39" },
			{ name: "नाशिक", code: "19" },
			{ name: "परभणी", code: "31" },
			{ name: "पालघर", code: "45" },
			{ name: "पुणे", code: "21" },
			{ name: "बीड", code: "26" },
			{ name: "बुलढाणा", code: "34" },
			{ name: "भंडारा", code: "36" },
			{ name: "मंबई", code: "11" },
			{ name: "यवतमाळ", code: "35" },
			{ name: "रत्नागिरी", code: "13" },
			{ name: "रायगड", code: "12" },
			{ name: "लातूर", code: "28" },
			{ name: "वर्धा", code: "40" },
			{ name: "वाशिम", code: "42" },
			{ name: "सांगली", code: "22" },
			{ name: "सातारा", code: "23" },
			{ name: "सोलापूर", code: "24" },
			{ name: "हिंगोली", code: "43" }
		  ]
		  
	},
	CommodityGird : {
		name : "शेतमाल निहाय/CommodityGird",
		tableId : "CommodityGird",
		SelectOptionId : "drpCommodities",
		tableName : "CommodityGird",
		subTabID : "CommodityGirdID",
		DropdownOptions : [
			{ name: "अंजीर", code: "07003" },
			{ name: "अंजीर (सुके)", code: "10027" },
			{ name: "अंबाडी भाजी", code: "08003" },
			{ name: "अननस", code: "07002" },
			{ name: "अर्वी", code: "08005" },
			{ name: "अवाकाडो", code: "18008" },
			{ name: "आंबट चुका", code: "08004" },
			{ name: "आंबा", code: "07001" },
			{ name: "आईसबर्ग", code: "18003" },
			{ name: "आले", code: "08002" },
			{ name: "आले (सुंठ)", code: "10001" },
			{ name: "आवळा", code: "07042" },
			{ name: "आवळा", code: "08006" },
			{ name: "उडीद", code: "03022" },
			{ name: "उडीद डाळ", code: "03023" },
			{ name: "एरंडी", code: "04005" },
			{ name: "ओवा", code: "04014" },
			{ name: "कंद", code: "08034" },
			{ name: "कडबा", code: "11003" },
			{ name: "कढिपत्ता", code: "08031" },
			{ name: "करडई", code: "04008" },
			{ name: "करडई (भाजी)", code: "08038" },
			{ name: "कलिंगड", code: "07011" },
			{ name: "कांदा", code: "08035" },
			{ name: "कांदा पात", code: "08036" },
			{ name: "काकडी", code: "08033" },
			{ name: "काजू", code: "10010" },
			{ name: "कापूस", code: "01001" },
			{ name: "कारली", code: "08039" },
			{ name: "कालवड", code: "09020" },
			{ name: "कुलथी", code: "03010" },
			{ name: "केळी", code: "07014" },
			{ name: "केळी (कच्ची)", code: "08040" },
			{ name: "कैरी", code: "08032" },
			{ name: "कोंबडी", code: "09009" },
			{ name: "कोथिंबिर", code: "08044" },
			{ name: "कोबी", code: "08041" },
			{ name: "कोहळा", code: "08043" },
			{ name: "खरबुज", code: "07044" },
			{ name: "गवार", code: "08024" },
			{ name: "गहू", code: "02009" },
			{ name: "गाजर", code: "08022" },
			{ name: "गाय", code: "09005" },
			{ name: "गुलाब", code: "16003" },
			{ name: "गुळ", code: "06001" },
			{ name: "घेवडा", code: "08025" },
			{ name: "घेवडा बी", code: "03005" },
			{ name: "घोडा", code: "09006" },
			{ name: "घोसाळी (भाजी)", code: "08026" }
		] 
	}
}

module.exports = marketTypesDetails;